### ISSUE TITLE
Does this support Anonymous requests?

### ISSUE THREAD

**Issue by eschneider999** [blowdart/idunno.Authentication#18]
Does this support Anonymous requests ?

Has this been tested in .net core 2.1 ?

**Comment by blowdart** [comment]
Neither take effect until you hit an [Authorize] controller action, but certificate is fussier, because that's at the transport layer. While you can configure the transport to make certs optional, you can't kick the user back to the cert prompt, so it'll just tell them unauthorized, so with certs the only working choice is "Certificate only", with no anonymous support.

It hasn't been tested with 2.1, but we didn't change anything really so it should work.

**Comment by eschneider999** [comment]
that's confusing. Let's assume we have a cert.

My question is does it only force auth for items that are attributed with [Authorize] ? 
Can I have a controller action that's Anonymous?

**Comment by blowdart** [comment]
Like I said it depends on which auth package you're talking about. Basic auth yes, certificate auth no.

**Comment by eschneider999** [comment]
ahh, sorry missed the two packages point.

Yes I talking about the Basic auth.
Thanks

**Comment by blowdart** [comment]
Yup it'll work then, but the way basic auth works once a user has entered their username and password it's going to be sent with every request, even if you have an anonymous controller. You won't see an identity though, because MVC won't make one for anonymous controllers, but the headers will be there.

**Comment by eschneider999** [comment]
quick question.

How would I retrieve setting/connection string for my user check?
Before I was using the middleware approach, but now can't seem to get the settings.

    public class AuthenticationMiddleware<TOptions>
    {
        private readonly RequestDelegate _next;
        private Settings _settings;

        /// <summary>
        /// 
        /// </summary>
        /// <param name="settings"></param>
        /// <param name="next"></param>
        public AuthenticationMiddleware(IOptions<Settings> settings, RequestDelegate next)
        {
            _next = next;
            _settings = settings.Value;
        }

**Comment by blowdart** [comment]
Ah that gets complicated somewhat. Options classes support DI, so what you can do is roll your own options class, inheriting from the supplied version, and put the settings class as a constructor argument, then retrieve it that way. Don't forget to set the right scope though, especially if you're using EF. @Tratcher has an example somewhere in the asp.net core samples I think, Chris could you link?

**Comment by Tratcher** [comment]
What was Middleware in 1.x is now Handlers in 2.x, but otherwise the IOptions works about the same as before. See https://github.com/blowdart/idunno.Authentication/blob/ce1b7ee6f2cb7b6b8d59639fd15591cc5be9cb50/src/idunno.Authentication.Basic/BasicAuthenticationHandler.cs#L22-L23
